---
- name: Send Daily Report Email
  when: email_enabled
  mail:
    host: "{{ smtp_host }}"
    port: "{{ smtp_port }}"
    from: "{{ email_from }}"
    to: "{{ email_to }}"
    cc: "{{ email_cc | default(omit) }}"
    subject: "{{ email_subject }}"
    body: |
      Hello Team,

      Please find attached the OCI DAILY Cost & Usage Report.

      Report Period : DAILY
      Generated On  : {{ ansible_date_time.iso8601 }}

      Regards,
      OCI Reporting Automation
    attach:
      - "{{ reports_dir }}/oci_daily_report_{{ ts_file }}.xlsx"
